### ISSUE TITLE
Global Lookup

### ISSUE THREAD

**Issue by JodieM** [danhowellnz/Flow-Action---Get-collection#2]
Where is the Global Lookup component mentioned in your documentation? I can't see it in the contents of package version 1.1

**Comment by danhowellnz** [comment]
That is a good question. Just added it to the git.

And changed the package link to 
/packaging/installPackage.apexp?p0=04t7F000005QzIG

**Comment by JodieM** [comment]
Thanks Dan! Any hints on how to "update" the package - when it's already installed, and I don't want to have to delete ALL my flows, uninstall your package, and start again

**Comment by danhowellnz** [comment]
Because it's unmanaged code you need to push it in. Ideally you do this in sfdx. 

So install it in a sandbox. Then create a change set to push it across. This will overwrite the code

**Comment by JodieM** [comment]
Thanks that works now. Heads up if anyone is "upgrading" from the previous version 1.1 to this version 1.1, you have to edit each one of these Actions in your Flow Canvas to remove the text collection variable from the Search Scope or it will give you an error message that one of your Actions has an issue, when it's actually all of them. I will raise a separate ticket for the Search
