### ISSUE TITLE
Output No. of Records Found

### ISSUE THREAD

**Issue by JodieM** [danhowellnz/Flow-Action---Get-collection#3]
Great Action Dan, thank you! 

I would love the Output of the Action to also include the No. of Records found. I am passing the output into Eric Smith's Datatable so I would like to bypass the datatable screen if no records were found.

**Comment by JodieM** [comment]
Ah I guess I can use Alex's collections Count Action https://unofficialsf.com/list-actions-for-flow/

**Comment by danhowellnz** [comment]
No. There is a standard feature. Create an assign element. 

Then make a number variable to store the count in.  

Instead and in the assign element luckiest there is equals count. 

https://www.google.com/amp/s/jenwlee.com/2018/06/26/blink-you-may-have-missed-this-hidden-gem-get-count-via-flow-assignment/amp/

**Comment by JodieM** [comment]
Ah of course, thank you!
