### ISSUE TITLE
Search Scope no longer allows a Text Collection variable

### ISSUE THREAD

**Issue by JodieM** [danhowellnz/Flow-Action---Get-collection#4]
The documentation shows the bit of adding to a text collection variable for the Search Scope, but the Search Scope field no longer allows for a text collection variable. It may just need to be an update to remove that from the documentation, but it was a nice feature in the previous version 1.1. 

Here's my video of it https://www.loom.com/share/4e76639b3cc049749d4a6d97b7b3bdce

**Comment by danhowellnz** [comment]
It should be a bit more up to date now: https://gravitylab.nz/wp-admin/post.php?post=554&action=elementor

Thanks for this. Sorry I missed it.
