### ISSUE TITLE
Certain characters cause action to crash

### ISSUE THREAD

**Issue by adwhite75** [danhowellnz/Flow-Action---Get-collection#5]
Awesome action Dan! I was playing around with and noticed an issue with the query. See below for details

FLOWFINDCOLLECTION (APEX): Find_Contacts_via_Search_Term
Inputs:
sObjectName = Contact
FieldApiINames = Id,Name,Email,AccountId
BypassSharing = true
queries = {!inputSearch_Contacts} (adam!)
scope = ALL FIELDS
WhereLimit = 40
Error Occurred: An Apex error occurred: System.QueryException: line 1:10 mismatched character '!' expecting '}'

Looks like having certain characters will cause the query to crash out. Looks like you need to escape some reserved characters in SOSL: https://developer.salesforce.com/forums/?id=906F00000009EySIAU

**Comment by systemsfixer** [comment]
I encountered this issue too.

I'm using a utility class from Doug Ayers to smooth this over, but will need to modify it to be flow invocable. 

https://github.com/douglascayers/sfdc-escape-sosl

**Comment by danhowellnz** [comment]
This is perfect - thank you!

**Comment by danhowellnz** [comment]
I have updated the link: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t7F000005QzeN
